### ISSUE TITLE
Add support windows server

### ISSUE THREAD

**Issue by bob2build** [vkhatri/chef-topbeat#13]
Similar to filebeat cookbook, this cookbook should also support for windows, I shall submit a pull request in couple of days.

**Comment by vkhatri** [comment]
@bob2build 👍

**Comment by bob2build** [comment]
I have been held in other tasks for a while. I have added support for installing topbeat on windows. 
https://github.com/vkhatri/chef-topbeat/pull/14
This pull also includes kitchen integration tests for other platforms.

**Comment by vkhatri** [comment]
@bob2build 👍
